project:
    name: 'facial-recognition-demo'
    container: 'bigdata'
    docker_image: 'facial-recognition-demo-image'
stream:
    raw_video_stream: 'videostream'
    tagged_video_stream: 'taggedvideos'
    rotate_180: 'True' # Fix for VLC broadcasting stream rotated 180 degrees
    shard_id: "0"
camera:
    list_table: 'camera_list'
    id: "0"
    url: "http://XXX.XXX.X.XXX:XXXX"
api:
    gateway: 'camera-img'
    facial_recognition_function: 'deploy-facial-recognition'
    get_image_function: 'deploy-image-retrieval'
    auth: "XXXXXXXXXXX"