project:
    name: 'facial-recognition-demo'
    container: 'bigdata'
    docker_image: 'facial-recognition-demo-image'
stream:
    raw_video_stream: 'videostream'
    tagged_video_stream: 'taggedvideos'
    rotate_180: 'True' # Fix for VLC broadcasting stream rotated 180 degrees
    shard_id: "0"
camera:
    list_table: 'camera_list'
    id: "0"
    url: "http://192.168.0.103:8080"
api:
    gateway: 'camera-img'
    facial_recognition_function: 'deploy-facial-recognition'
    get_image_function: 'deploy-image-retrieval'
    auth: "IL!keD@t@123"
v3io:
    webapi: "https://webapi.default-tenant.app.us-sales.iguazio-cd2.com"
    frames: "https://framesd.default-tenant.app.us-sales.iguazio-cd2.com"
    username: "nick"
    access_key: "a39443ce-d2c1-46e5-b821-24f3a6116cc4"
