name: facial-recognition-demo
functions:
- url: ../components/notebooks/CreateStreamsTables.ipynb
  name: create-streams-tables
  kind: job
- url: ../components/notebooks/DeployFacialRecognition.ipynb
  name: deploy-facial-recognition
  kind: nuclio
- url: ../components/notebooks/DeployImageRetrieval.ipynb
  name: deploy-image-retrieval
  kind: nuclio
- url: ../components/notebooks/CreateAPIGateway.ipynb
  name: create-api-gateway
  kind: job
- url: ../components/notebooks/CreateGrafanaDashboard.ipynb
  name: create-grafana-dashboard
  kind: job
workflows:
- name: main
  path: workflow.py
artifacts: []
artifact_path: ''
